import js from "@eslint/js";

export default [
  {
    ...js.configs.recommended,
    files: ["static/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      // Browser globals that are always available
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        location: "readonly",
        alert: "readonly",
        prompt: "readonly",
        navigator: "readonly",
        requestAnimationFrame: "readonly",
        MutationObserver: "readonly",
        cancelAnimationFrame: "readonly",
        sessionStorage: "readonly",
        localStorage: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        history: "readonly",
        // App globals from app.js consumed by templates
        _csrfFetch: "readonly",
        _csrfToken: "readonly",
        _authJson: "readonly",
        STATUS_BADGE: "readonly",
        STATUS_ROW: "readonly",
        LUCILA_YANEZ: "readonly",
        MOISES_BUSTOS: "readonly",
        preparerListLabelJs: "readonly",
        initInlineEdit: "readonly",
        inlineFieldDisplay: "readonly",
        initSearch: "readonly",
        initTableFilter: "readonly",
        toggleStatusMenu: "readonly",
        escHtml: "readonly",
        marked: "readonly",
      },
    },
    rules: {
      "no-redeclare":        "error",
      "no-unused-vars":      ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^(toggleStatusMenu|setStatus|submitNote|preparerListLabelJs|initSearch|initInlineEdit|initTableFilter|escHtml)$" }],
      "no-undef":            "error",
      "no-var":              "error",
    },
  },
];
