# PROD-4 — Register Windows Task Scheduler job for nightly TaxOps SQLite backup (GitHub #92).
#
# Run once as Administrator on the file server that hosts the TaxOps share
# (SYSTEM cannot see mapped T: drives). Safe to re-run; replaces the existing task.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\register-nightly-backup-task.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\register-nightly-backup-task.ps1 -RunNow

[CmdletBinding()]
param(
    [switch]$RunNow
)

$ErrorActionPreference = 'Stop'

$TaskName = 'TaxOpsNightlyDbBackup'

function Convert-ToUncIfMapped {
    param([Parameter(Mandatory)][string]$Path)
    $resolved = (Resolve-Path -LiteralPath $Path).Path
    if ($resolved -match '^[A-Za-z]:') {
        $drive = $resolved.Substring(0, 2)
        $rest = $resolved.Substring(2).TrimStart('\')
        $map = (cmd /c "net use $drive" 2>$null) -join "`n"
        if ($map -match '\\\\[^\s]+') {
            $uncRoot = $Matches[0].TrimEnd('\')
            if ($rest) { return (Join-Path $uncRoot $rest) }
            return $uncRoot
        }
    }
    return $resolved
}

# This script: <share>/taxops/scripts/register-nightly-backup-task.ps1
$AppDirLocal = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$ShareRootLocal = (Resolve-Path (Join-Path $AppDirLocal '..')).Path
$ShareUnc = Convert-ToUncIfMapped $ShareRootLocal
$AppUnc = Join-Path $ShareUnc 'taxops'
$BackupDir = Join-Path $ShareUnc 'backups'
$WrapperBat = Join-Path $BackupDir 'run_nightly_backup.bat'
$ErrorLog = Join-Path $BackupDir 'backup_error.log'

if (-not (Test-Path -LiteralPath (Join-Path $AppDirLocal 'scripts\nightly_backup_db.py'))) {
    throw "Backup script missing under $AppDirLocal"
}

New-Item -ItemType Directory -Force -Path $BackupDir | Out-Null

# Runtime-resolving wrapper: prefers server-local C:\TaxOps, then UNC share.
# Avoids baking a workstation Store-python path into the scheduled task.
$wrapper = @"
@echo off
REM Auto-generated by register-nightly-backup-task.ps1 — regenerate by re-running that script.
setlocal
set "BACKUP_DIR=$BackupDir"
set "ERRLOG=$ErrorLog"
set "APP="
if exist "C:\TaxOps\taxops\scripts\nightly_backup_db.py" set "APP=C:\TaxOps\taxops"
if not defined APP if exist "$AppUnc\scripts\nightly_backup_db.py" set "APP=$AppUnc"
if not defined APP (
  echo [%date% %time%] FAILED: taxops app dir not found >> "%ERRLOG%"
  exit /b 1
)
set "TAXOPS_DB=%APP%\taxops.db"
set "TAXOPS_BACKUP_DIR=%BACKUP_DIR%"
set "TAXOPS_BACKUP_ERROR_LOG=%ERRLOG%"
set "PY="
if exist "%APP%\.venv\Scripts\python.exe" set "PY=%APP%\.venv\Scripts\python.exe"
if not defined PY if exist "C:\TaxOps\taxops\.venv\Scripts\python.exe" set "PY=C:\TaxOps\taxops\.venv\Scripts\python.exe"
if not defined PY where py >nul 2>&1 && set "PY=py"
if not defined PY where python >nul 2>&1 && set "PY=python"
if not defined PY (
  echo [%date% %time%] FAILED: no Python found for nightly backup >> "%ERRLOG%"
  exit /b 1
)
pushd "%APP%"
if errorlevel 1 (
  echo [%date% %time%] FAILED: pushd "%APP%" >> "%ERRLOG%"
  exit /b 1
)
"%PY%" scripts\nightly_backup_db.py
set ERR=%ERRORLEVEL%
popd
exit /b %ERR%
"@
Set-Content -LiteralPath $WrapperBat -Value $wrapper -Encoding ASCII

Write-Host "Share UNC  : $ShareUnc"
Write-Host "App UNC    : $AppUnc"
Write-Host "BackupDir  : $BackupDir"
Write-Host "Wrapper    : $WrapperBat"

$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "Removing existing scheduled task '$TaskName'."
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument "/c `"$WrapperBat`""
$trigger = New-ScheduledTaskTrigger -Daily -At '2:10AM'
$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' `
    -LogonType ServiceAccount -RunLevel Highest
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2)

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Principal $principal `
    -Settings $settings `
    -Description 'PROD-4 TaxOps nightly SQLite backup (WAL-safe). See backups\run_nightly_backup.bat.' | Out-Null

Write-Host "Registered '$TaskName' (daily 2:10 AM as SYSTEM)." -ForegroundColor Green

if ($RunNow) {
    Write-Host "Starting test run..."
    schtasks.exe /Run /TN $TaskName | Out-Null
    Start-Sleep -Seconds 5
    $info = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Host ("LastTaskResult={0} LastRunTime={1}" -f $info.LastTaskResult, $info.LastRunTime)
    if (Test-Path -LiteralPath $ErrorLog) {
        Write-Host "--- backup_error.log (tail) ---"
        Get-Content -LiteralPath $ErrorLog -Tail 5
    }
}

Write-Host ""
Write-Host "Verify:"
Write-Host "  schtasks.exe /Run /TN `"$TaskName`""
Write-Host "  Get-ScheduledTask -TaskName $TaskName"
Write-Host "  Get-ChildItem `"$BackupDir\taxops_backup_*.sqlite`" | Sort LastWriteTime -Descending | Select -First 5"
